METplus: metplus.wrappers.tc_gen_wrapper.TCGenWrapper Class Reference
metplus.wrappers.tc_gen_wrapper.TCGenWrapper Class Reference
Detailed Description
Definition at line 28 of file tc_gen_wrapper.py.
Public Member Functions
def __init__ (self, config, instance=None, config_overrides={})
def create_c_dict (self)
def get_filter_values (self)
find all TC_GEN_FILTER_<n> values in the config files
def get_command (self)
def run_all_times (self)
Runs the MET application for a given run time.
def run_at_time (self, input_dict)
Process runtime and try to build command to run ascii2nc Args:
def run_at_time_once (self, time_info)
Process runtime and try to build command to run ascii2nc Args:
def find_input_files (self, time_info)
Get track and genesis files and set c_dict items.
def set_command_line_arguments (self, time_info)
Public Attributes
app_name
app_path
Static Public Attributes
list WRAPPER_ENV_VAR_KEYS
Member Function Documentation
find_input_files()
def metplus.wrappers.tc_gen_wrapper.TCGenWrapper.find_input_files (self, time_info)
Get track and genesis files and set c_dict items.
Also format forecast lead sequence to be read by the MET configuration file and set c_dict.
Parameters
time_info time dictionary to use for string substitution
Returns
True if all inputs were found, False if not.
Definition at line 360 of file tc_gen_wrapper.py.
Referenced by metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), and metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time_once().
run_all_times()
def metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_all_times (self)
Runs the MET application for a given run time.
This function loops over the list of forecast leads and runs the application for each.
Parameters
input_dict dictionary containing timing information
Definition at line 308 of file tc_gen_wrapper.py.
run_at_time()
def metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time (self, input_dict)
Process runtime and try to build command to run ascii2nc Args:
Parameters
input_dict dictionary containing timing information
Definition at line 319 of file tc_gen_wrapper.py.
Referenced by metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), and metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_all_times().
run_at_time_once()
def metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time_once (self, time_info)
Process runtime and try to build command to run ascii2nc Args:
Parameters
time_info dictionary containing timing information
Definition at line 338 of file tc_gen_wrapper.py.
Referenced by metplus.wrappers.runtime_freq_wrapper.RuntimeFreqWrapper.run_all_times_custom(), metplus.wrappers.runtime_freq_wrapper.RuntimeFreqWrapper.run_at_time(), metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time(), and metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time().
Member Data Documentation
WRAPPER_ENV_VAR_KEYS
list metplus.wrappers.tc_gen_wrapper.TCGenWrapper.WRAPPER_ENV_VAR_KEYS static
Initial value:
=  [
        'METPLUS_INIT_FREQ',
        'METPLUS_LEAD_WINDOW_DICT',
        'METPLUS_MIN_DURATION',
        'METPLUS_FCST_GENESIS_DICT',
        'METPLUS_BEST_GENESIS_DICT',
        'METPLUS_OPER_GENESIS_DICT',
        'METPLUS_FILTER',
        'METPLUS_DESC',
        'METPLUS_MODEL',
        'METPLUS_STORM_ID',
        'METPLUS_STORM_NAME',
        'METPLUS_INIT_BEG',
        'METPLUS_INIT_END',
        'METPLUS_VALID_BEG',
        'METPLUS_VALID_END',
        'METPLUS_INIT_HOUR',
        'METPLUS_LEAD_LIST',
        'METPLUS_VX_MASK',
        'METPLUS_GENESIS_WINDOW_DICT',
        'METPLUS_GENESIS_RADIUS',
        'METPLUS_DLAND_FILE',
    ]
Definition at line 30 of file tc_gen_wrapper.py.
The documentation for this class was generated from the following file:
/home/mccabe/create-4.0.0-beta4-release/METplus/metplus/wrappers/tc_gen_wrapper.py