METplus: metplus.wrappers.mode_wrapper.MODEWrapper Class Reference
metplus.wrappers.mode_wrapper.MODEWrapper Class Reference
Wrapper for the mode MET tool.
Detailed Description
Wrapper for the mode MET tool.
Definition at line 19 of file mode_wrapper.py.
Public Member Functions
def __init__ (self, config, instance=None, config_overrides={})
def add_merge_config_file (self, time_info)
If merge config file is defined, add it to the command.
def create_c_dict (self)
def set_environment_variables (self, time_info)
Set environment variables that will be read set when running this tool.
def run_at_time_one_field (self, time_info, var_info)
Runs mode instances for a given time and forecast lead combination Overrides run_at_time_one_field function in compare_gridded_wrapper.py Args:
def process_fields_one_thresh (self, time_info, var_info, model_path, obs_path)
For each threshold, set up environment variables and run mode Args:
Public Attributes
app_name
app_path
isOK
param
Static Public Attributes
list WRAPPER_ENV_VAR_KEYS
Member Function Documentation
process_fields_one_thresh()
def metplus.wrappers.mode_wrapper.MODEWrapper.process_fields_one_thresh (self, time_info, var_info, model_path, obs_path)
For each threshold, set up environment variables and run mode Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information
model_path forecast file
obs_path observation file
Definition at line 207 of file mode_wrapper.py.
Referenced by metplus.wrappers.mtd_wrapper.MTDWrapper.run_at_time_loop_string(), and metplus.wrappers.mode_wrapper.MODEWrapper.run_at_time_one_field().
run_at_time_one_field()
def metplus.wrappers.mode_wrapper.MODEWrapper.run_at_time_one_field (self, time_info, var_info)
Runs mode instances for a given time and forecast lead combination Overrides run_at_time_one_field function in compare_gridded_wrapper.py Args:
Parameters
time_info dictionary containing timing information
var_info object containing variable information
Definition at line 187 of file mode_wrapper.py.
Referenced by metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation().
set_environment_variables()
def metplus.wrappers.mode_wrapper.MODEWrapper.set_environment_variables (self, time_info)
Set environment variables that will be read set when running this tool.
Parameters
time_info dictionary containing timing info for current run
Definition at line 156 of file mode_wrapper.py.
Referenced by metplus.wrappers.series_analysis_wrapper.SeriesAnalysisWrapper.build_and_run_series_request(), metplus.wrappers.make_plots_wrapper.MakePlotsWrapper.create_c_dict(), metplus.wrappers.pcp_combine_wrapper.PCPCombineWrapper.get_accumulation(), metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.process_data(), metplus.wrappers.mode_wrapper.MODEWrapper.process_fields_one_thresh(), metplus.wrappers.mtd_wrapper.MTDWrapper.process_fields_one_thresh(), metplus.wrappers.tc_pairs_wrapper.TCPairsWrapper.run_all_times(), metplus.wrappers.py_embed_ingest_wrapper.PyEmbedIngestWrapper.run_at_time(), metplus.wrappers.tc_stat_wrapper.TCStatWrapper.run_at_time(), metplus.wrappers.gen_vx_mask_wrapper.GenVxMaskWrapper.run_at_time_all(), metplus.wrappers.user_script_wrapper.UserScriptWrapper.run_at_time_once(), metplus.wrappers.gempak_to_cf_wrapper.GempakToCFWrapper.run_at_time_once(), metplus.wrappers.plot_data_plane_wrapper.PlotDataPlaneWrapper.run_at_time_once(), metplus.wrappers.point2grid_wrapper.Point2GridWrapper.run_at_time_once(), metplus.wrappers.tcrmw_wrapper.TCRMWWrapper.run_at_time_once(), metplus.wrappers.pb2nc_wrapper.PB2NCWrapper.run_at_time_once(), metplus.wrappers.tc_gen_wrapper.TCGenWrapper.run_at_time_once(), metplus.wrappers.regrid_data_plane_wrapper.RegridDataPlaneWrapper.run_at_time_once(), and metplus.wrappers.stat_analysis_wrapper.StatAnalysisWrapper.run_stat_analysis_job().
Member Data Documentation
WRAPPER_ENV_VAR_KEYS
list metplus.wrappers.mode_wrapper.MODEWrapper.WRAPPER_ENV_VAR_KEYS static
Initial value:
=  [
        'METPLUS_MODEL',
        'METPLUS_DESC',
        'METPLUS_OBTYPE',
        'METPLUS_REGRID_DICT',
        'METPLUS_QUILT',
        'METPLUS_FCST_FIELD',
        'METPLUS_FCST_CONV_RADIUS',
        'METPLUS_FCST_CONV_THRESH',
        'METPLUS_FCST_MERGE_THRESH',
        'METPLUS_FCST_MERGE_FLAG',
        'METPLUS_OBS_FIELD',
        'METPLUS_OBS_CONV_RADIUS',
        'METPLUS_OBS_CONV_THRESH',
        'METPLUS_OBS_MERGE_THRESH',
        'METPLUS_OBS_MERGE_FLAG',
        'METPLUS_MASK_POLY',
        'METPLUS_OUTPUT_PREFIX',
    ]
Definition at line 22 of file mode_wrapper.py.
The documentation for this class was generated from the following file:
/d1/personal/jpresto/METplus/git/METplus/metplus/wrappers/mode_wrapper.py